<?php

/**
 * @file
 * Contains remove_format_help.module.
 */

use Drupal\Core\Form\FormStateInterface;

function linkit_description_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $description = "Start typing to find internal content or to insert an email address. To add an external link paste the full URL (e.g. http://www.example.com).";
  if ($form_id == "linkit_editor_dialog_form") {
    $form['attributes']['href']['#description'] = t($description);
  }
}
