# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2

jobs:
  # Tests the integrity of the build, stores the results in a workspace for re-use in later jobs.
  build:
    docker:
      - image: circleci/php:7.2.20-apache-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f0:33:18:e6:c8:6c:76:6c:07:1f:76:af:c9:8f:4a:66"
      - checkout
      - run:
          name: Validate composer.json and composer.lock file for consistency
          command: composer validate --no-check-all --strict
      - run:
          name: Add GitHub access token for composer
          command: echo 'composer config -g github-oauth.github.com $GITHUB_TOKEN' >> $BASH_ENV
      - run:
            name: Add OS and PHP extensions
            command: |
              sudo apt-get update
              sudo apt-get install -y libpng-dev
              sudo docker-php-ext-install gd
              composer global require hirak/prestissimo
      - restore_cache:
          keys:
          - composer-{{ checksum "composer.lock" }}
      - run:
          name: Fetch dependencies with composer
          command: |
            composer install --no-interaction --optimize-autoloader
            composer drupal:scaffold
            composer run-script post-install-cmd
      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - $HOME/.composer/cache
      - run:
          name: Update any projects on dev branches
          command: |
            REPOS=(
              modules/origins
              profiles/custom/origins
            )
            for repo in "${REPOS[@]}"
            do
              cd /home/circleci/project/web/$repo
              if [[ $(git symbolic-ref --short HEAD) ]]; then
                echo "Fetching latest contents of repository at /home/circleci/project/web/${repo}"
                git pull
              else
                echo "Skipping /home/circleci/project/web/${repo} as it is presently checked out on release tag"
              fi
            done
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  # Test for coding standards and deprecated code.
  static_analysis:
    docker:
      - image: circleci/php:7.2.20-apache-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f0:33:18:e6:c8:6c:76:6c:07:1f:76:af:c9:8f:4a:66"
      - attach_workspace:
          at: ./
      - run:
          name: Add OS and PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install gd
            composer global require hirak/prestissimo
      - run:
          name: PHPCS static analysis
          command: /home/circleci/project/phpcs.sh /home/circleci/project "/home/circleci/project/web/modules/origins /home/circleci/project/web/modules/custom /home/circleci/project/web/themes/custom"
      - run:
         name: Deprecated code check
         command: |
            cd /home/circleci/project
            vendor/bin/drupal-check /home/circleci/project/web/modules/custom /home/circleci/project/web/modules/origins

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - static_analysis:
          requires:
            - build
