# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2

jobs:
  # Tests the integrity of the build, stores the results in a workspace for re-use in later jobs.
  build:
    docker:
      - image: circleci/php:7.2.20-apache-browsers
    steps:
      - checkout
      - run:
          name: Validate composer.json and composer.lock file for consistency
          command: composer validate --no-check-all --strict
      - run:
          name: Add GitHub access token for composer
          command: echo 'composer config -g github-oauth.github.com $GITHUB_TOKEN' >> $BASH_ENV
      - run:
            name: Add OS and PHP extensions
            command: |
              sudo apt-get update
              sudo apt-get install -y libpng-dev
              sudo docker-php-ext-install gd
              composer global require hirak/prestissimo
      - restore_cache:
          keys:
          - composer-{{ checksum "composer.lock" }}
      - run:
          name: Fetch dependencies with composer
          command: |
            composer install --no-interaction --optimize-autoloader
            composer drupal:scaffold
            composer run-script post-install-cmd
      - save_cache:
          key: composer-{{ checksum "composer.lock" }}
          paths:
            - $HOME/.composer/cache
      - run:
          name: Update any projects on dev branches
          command: |
            REPOS=(
              modules/custom
              modules/origins
              profiles/custom/origins
            )
            for repo in "${REPOS[@]}"
            do
              cd /home/circleci/project/web/$repo
              if [[ $(git symbolic-ref --short HEAD) ]]; then
                echo "Fetching latest contents of repository at /home/circleci/project/web/${repo}"
                git pull
              else
                echo "Skipping /home/circleci/project/web/${repo} as it is presently checked out on release tag"
              fi
            done
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  # Test for coding standards and deprecated code.
  static_analysis:
    docker:
      - image: circleci/php:7.2.20-apache-browsers
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Add OS and PHP extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y libpng-dev
            sudo docker-php-ext-install gd
            composer global require hirak/prestissimo
      - run:
          name: PHPCS static analysis
          command: /home/circleci/project/phpcs.sh /home/circleci/project "/home/circleci/project/web/modules/origins /home/circleci/project/web/modules/custom /home/circleci/project/web/themes/custom"
      - run:
         name: Deprecated code check
         command: |
            cd /home/circleci/project
            vendor/bin/drupal-check /home/circleci/project/web/modules/custom /home/circleci/project/web/modules/origins

  # Run any unit tests and any kernel tests against a vanilla D8 site + our site config imported over it (no predefined content).
  unit_kernel_tests:
    docker:
      - image: circleci/php:7.2.20-apache-browsers
      - image: circleci/mysql:5.7.27
    steps:
      - attach_workspace:
          at: ./
      - run:
            name: Add OS and PHP extensions/config
            command: |
              sudo cp /home/circleci/project/.circleci/docker-php-circleci.ini /usr/local/etc/php/conf.d/
              sudo apt-get update
              sudo apt-get install -y libpng-dev mariadb-client rsync
              sudo docker-php-ext-install gd pdo_mysql
              composer global require hirak/prestissimo
      - run:
            name: Copy vhost into place
            command: |
              sudo cp .circleci/drupal.vhost /etc/apache2/sites-available/drupal.conf
      - run:
            name: Enable web server and vhosts
            command: |
              sudo a2enmod rewrite
              sudo a2dissite 000-default
              sudo a2ensite drupal
              sudo service apache2 start
      - run:
            name: Install Drupal and configure settings
            command: |
              # Should be scaffolded by now.
              cd /home/circleci/project/web
              cp sites/default/default.settings.php sites/default/settings.php
              cp sites/default/default.services.yml sites/default/services.yml
              # Copy in our environment specific settings to the settings.php file.
              cp /home/circleci/project/.circleci/drupal.settings.php sites/default/settings.php
              # Copy PHPUnit config into core folder.
              cp /home/circleci/project/.circleci/phpunit.circleci.xml core/
              # Install Drupal (or restore from DB dump at this point).
              ../vendor/bin/drush site-install -y --existing-config
      - run:
            name: Copy files into webroot
            command: |
              # Copy our build into position (./ suffix ensures hidden files are copied too).
              sudo rsync -avq /home/circleci/project/. /var/www/html
      - run:
            name: PHPUnit tests (unit)
            command: |
              cd /var/www/html/web/core
              ../../vendor/bin/phpunit -c /var/www/html/web/core/phpunit.circleci.xml --testsuite unit --group nicsdru_origins
      - run:
            name: PHPUnit tests (kernel)
            command: |
              cd /var/www/html/web/core
              ../../vendor/bin/phpunit -c /var/www/html/web/core/phpunit.circleci.xml --testsuite kernel --group nicsdru_origins

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - static_analysis:
          requires:
            - build
      - unit_kernel_tests:
          requires:
            - build
